# Generated by Django 2.2.3 on 2019-07-26 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_DB', '0002_auto_20190725_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemhistory',
            name='date_bought',
            field=models.DateField(default=datetime.date(2019, 7, 26)),
        ),
        migrations.AlterField(
            model_name='itemhistory',
            name='date_sold',
            field=models.DateField(default=datetime.date(2019, 7, 26)),
        ),
    ]
